#!/bin/sh
# Copyright (C) 2026 spiderr
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.

# logfetchupdate
# 
# Connect to one/any of the xymon servers and attempt to download an updated copy 
# of our logfetch config file.
# 
# Server must support this syntax ... Terabithia RPMS > 4.3.18
# 

test -z "$XYMONTMP" && echo "ERROR: xymon environment not present" >&2 && exit -1

# Set these in sysconfig or xymonclient.cfg
test "$STATUSMODE" = "yes" -o "$SUBMITMODE" = "yes" || exit 0

# Allow an override of the "standard" XYMSRV entry
test -n "$XYMCONFIGSRV" && XYMSRV="$XYMCONFIGSRV"

LOGFETCHCFG=$XYMONTMP/logfetch.$MACHINEDOTS.cfg
export LOGFETCHCFG


rm -f "$LOGFETCHCFG.$$.tmp"

$XYMON $XYMSRV "clientconfig $MACHINE.$SERVEROSTYPE $CONFIGCLASS" > "$LOGFETCHCFG.$$.tmp"
RES="$?"

if test -f "$LOGFETCHCFG.$$.tmp"
then
	if test -s "$LOGFETCHCFG.$$.tmp"
	then
		mv "$LOGFETCHCFG.$$.tmp" "$LOGFETCHCFG"
		exit 0
	else
		rm -f "$LOGFETCHCFG.$$.tmp"
		exit $RES
	fi
fi
